plugins {
    id 'java-library'
    id 'maven-publish'
    id 'signing'
}

description = 'This is a patched version of ed25519-java, an implementation of EdDSA in Java. The orginal implementation can be found here https://github.com/str4d/ed25519-java'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation 'org.hamcrest:hamcrest-all:1.3'
    testImplementation 'junit:junit:4.13.2'
}

sourceSets {
    main {
        java {
            srcDirs = ['src']
        }
    }
    test {
        java {
            srcDirs = ['test']
        }
        resources {
            srcDirs = ['test']
            exclude '**/*.java'
        }
    }
}

sourceCompatibility = '1.7'

compileJava {
    sourceCompatibility = JavaVersion.VERSION_1_7
    targetCompatibility = JavaVersion.VERSION_1_7
    options.compilerArgs += ["-Aproject=${project.group}/${project.name}"]
}


task sourceJar(type: Jar) {
    classifier "sources"
    from sourceSets.main.allJava
}

task javadocJar(type: Jar, dependsOn: javadoc) {
    classifier "javadoc"
    from javadoc.destinationDir
}

artifacts {
    archives jar
    archives sourceJar
    archives javadocJar
}

test {
    useJUnit {

    }

    testLogging {
        showStandardStreams = true
    }
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java

            artifact(sourceJar) {
                classifier = 'sources'
            }
            artifact(javadocJar) {
                classifier = 'javadoc'
            }

            pom {
                name = 'EdDSA-Java_BloxBean_patch'

                description = 'This is a patched version of ed25519-java, an implementation of EdDSA in Java. The original implementation can be found here https://github.com/str4d/ed25519-java'
                url = 'https://github.com/bloxbean/ed25519-java'
                licenses {
                    license {
                        name = 'CC0 1.0 Universal'
                        url = 'https://creativecommons.org/publicdomain/zero/1.0/'
                    }
                }
                developers {
                    developer {
                        id = 'satran004'
                        name = 'Satya'
                        description = '''Maintainer of this patched version.
                         This project is based on the original ed25519-java implementation.
                         For the original project and developers, refer to: https://github.com/str4d/ed25519-java.
                         This version includes fixes and improvements for specific use cases.'''
                    }
                }
                scm {
                    connection = 'scm:git:git://github.com/bloxbean/ed25519-java.git'
                    developerConnection = 'scm:git:ssh://git@github.com/bloxbean/ed25519-java.git'
                    url = 'https://github.com/bloxbean/ed25519-java'
                }
            }
        }
    }

    repositories {
        String ossrhUsername = System.getenv('MAVEN_USERNAME')
        String ossrhPassword = System.getenv('MAVEN_PASSWORD')

        maven {
            def releasesRepoUrl = "https://oss.sonatype.org/service/local/staging/deploy/maven2"
            def snapshotsRepoUrl = "https://oss.sonatype.org/content/repositories/snapshots/"
            url = version.endsWith('SNAPSHOT') ? snapshotsRepoUrl : releasesRepoUrl
            credentials {
                username ossrhUsername
                password ossrhPassword
            }
        }
    }
}

ext.isReleaseVersion = !version.endsWith("SNAPSHOT")

if (isReleaseVersion && !project.hasProperty("skipSigning")) {
    signing {
        sign publishing.publications
    }
}
